# Generated by Django 4.2.7 on 2023-11-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_rename_nome_cliente_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='nome',
        ),
    ]
