# Generated by Django 4.2.7 on 2023-11-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_rename_username_cliente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
    ]
