# Generated by Django 4.2.7 on 2023-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_cliente_nome_alter_cliente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
