# Generated by Django 4.2.7 on 2023-11-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='tipo',
            field=models.CharField(choices=[('CD/CC', 'Cartão de Crédito/Débito'), ('CD', 'Cartão de Débito')], max_length=10, verbose_name='Tipo'),
        ),
    ]
