# Generated by Django 4.2.7 on 2023-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrato',
            name='movimentacoes',
        ),
        migrations.AddField(
            model_name='extrato',
            name='movimentacoes',
            field=models.ManyToManyField(related_name='movimentacoes', to='Contas.movimentacao'),
        ),
    ]
