# Generated by Django 4.2.7 on 2023-11-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaocredito',
            options={'verbose_name': 'Avaliação de Crédito', 'verbose_name_plural': 'Avaliações de Crédito'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
    ]
