# Generated by Django 4.2.7 on 2023-11-24 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0002_alter_avaliacaocredito_criacao_alter_cartao_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacaocredito',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='extrato',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
