# Generated by Django 4.2.7 on 2023-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0002_alter_cartao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='permitido',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
