# Generated by Django 4.2.7 on 2023-11-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0003_emprestimo_data_solicitacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('modificacao', models.DateField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratoCartao', to='Contas.cartao')),
                ('movimentacoesCartao', models.ManyToManyField(related_name='movimentacoesCartao', to='Contas.movimentacao')),
            ],
            options={
                'verbose_name': 'Extrato Cartao',
                'verbose_name_plural': 'Extratos Cartao',
            },
        ),
    ]
