# Generated by Django 4.2.7 on 2023-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0004_extratocartao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extratocartao',
            name='movimentacoesCartao',
        ),
        migrations.AddField(
            model_name='extratocartao',
            name='movimentacaoCartao',
            field=models.ManyToManyField(related_name='movimentacaoCartao', to='Contas.movimentacao'),
        ),
    ]
