# Generated by Django 4.2.7 on 2023-11-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contas', '0004_alter_movimentacao_conta_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='Contas.conta'),
        ),
    ]
